version: 2

project_name: perfdeck

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X main.version={{.Version}} -w -s

archives:
  - format: tar.gz
    # this name template makes the tar.gz title compatible with
    # standard package managers
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

brews:
  - name: perfdeck
    repository:
      owner: sumant1122
      name: homebrew-perfdeck
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/sumant1122/perfdeck"
    description: "A modern, lightweight, and customizable TUI performance monitor."
    license: "MIT"
    install: |
      bin.install "perfdeck"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
